#!/bin/sh

function setv() {
  vname=$1
  vval=$2
  
  eval "$vname=$vval"
  param="$param $vname=$vval"
}

param=""

# Set common variables
setv base_dir                         `cd $exec_dir/..;pwd`
setv bin_dir                          $base_dir/bin
setv Io_init_script                   $base_dir/share/landscape/scripts/init.io
