#!/bin/sh

function setv() {
  vname=$1
  vval=$2
  
  eval "$vname=$vval"
  param="$param $vname=$vval"
}

param=""

# Set common variables
setv base_dir                         `cd $exec_dir/..;pwd`
setv bin_dir                          $base_dir/bin
setv data_dir                         $base_dir/share/landscape
setv lib_dir                          $base_dir/lib/landscape
setv terrain_dir                      $data_dir/lod-terrains/compare
setv texture_dir                      $data_dir/textures
setv model_dir                        $data_dir/models
setv fonts_dir			      $data_dir/fonts
setv sounds_dir			      $data_dir/sounds

# Game configuration
#setv Game_xres			      800
#setv Game_yres			      600
#setv Game_fullscreen	              0
setv Game_xres			      1024
setv Game_yres			      768
setv Game_fullscreen	              1
setv Game_loading_screen              $texture_dir/loading-screen.spr

# Sound Manager configuration
setv SoundMan_sound_dir		      $sounds_dir

# Level of Detail Terrain Manager configuration
setv LoDQuadManager_terrain_prefix    $terrain_dir/terrain
setv LoDQuadManager_texture_prefix    $terrain_dir/texture
setv LoDQuadManager_texmap_prefix     $terrain_dir/texmap
setv LoDQuadManager_lightmap_prefix   $terrain_dir/lightmap
setv LoDQuadManager_quads_w           1
setv LoDQuadManager_quads_h           1
setv LoDQuadManager_detail_tex_name   $texture_dir/detail-texture.spr
setv LoDQuadManager_tile_dir          $texture_dir/terrain-tiles
setv LoDQuadManager_texture_list      $terrain_dir/textures

# Map configuration
setv Map_texture_file                 $terrain_dir/map.spr

# Camera configuration
setv Camera_focus                     1.5
setv Camera_aspect                    1.33333

# Sky (clouds layer) configuration
setv Sky_upside_texture_path          $texture_dir/sky-layer1-above.spr
setv Sky_downside_texture_path        $texture_dir/sky-layer1-below.spr

# SkyBox configuration
setv SkyBox_texture_path              $texture_dir/skybox/pastel

# Gunsight configuration
setv Gunsight_texture_file            $texture_dir/gunsight.spr

# SmokeTrail configuration
setv SmokeTrail_smoke_tex             $texture_dir/missile_smoke.spr
setv SmokeTrail_puffy_tex             $texture_dir/puffy_smoke.spr

# SmokeColumn configuration
setv SmokeColumn_puffy_tex            $texture_dir/puffy_smoke.spr

# Explosion configuration
setv Explosion_frames                 16
setv Explosion_seconds_per_frame      0.08
setv Explosion_filename_prefix        $texture_dir/explosion/explosion
setv Explosion_filename_postfix       .png
setv Explosion_size                   20.0
setv Explosion_sound                  explosion-01.wav

# Player configuration
setv Player_model_path                $model_dir/thunder
setv Player_model_file                $Player_model_path/thunder.obj
setv Player_model_bounds              $Player_model_path/thunder.bounds
setv Player_cannon_sound              cannon-shoot-1.wav

# Drone configuration
setv Drone_model_path                 $model_dir/thunder
setv Drone_model_file                 $Drone_model_path/thunder.obj
setv Drone_model_bounds               $Drone_model_path/thunder.bounds

# Tank configuration
setv Tank_model_path                  $model_dir/tank
setv Tank_base_file                   $Tank_model_path/base.obj
setv Tank_tower_file                  $Tank_model_path/tower.obj
setv Tank_cannon_file                 $Tank_model_path/cannon.obj
setv Tank_cannon_sound                cannon-shoot-1.wav
setv Tank_engine_sound_low            car-engine-1-loop.wav
setv Tank_engine_sound_high           car-engine-2-loop.wav

# FontMan configuration
setv FontMan_dir		      $fonts_dir
