#define ENABLE_DYNAMIC_LOD 1
#define ENABLE_TEXTURING 1
#define ENABLE_BIG_TEXTURE 1
#define ENABLE_NEIGHBOR_DEBUGGING 0
#define ENABLE_SPHERE_DEBUGGING 0
#define ENABLE_LIGHTMAP 1
#define ENABLE_FOG_LAYER 1

#define ERROR_FACTOR 200.0
//#define MAX_ERROR 0.005
//#define MAX_ERROR 1.0
#define MAX_ERROR 0.001

#define USE_Z_METRIC 0
#define USE_DISTANCE_METRIC 0
#define USE_ANGULAR_METRIC 0
#define USE_EDGE_METRIC 0
#define USE_BOUNDING_SPHERE_METRIC 0
#define USE_BOUNDING_SPHERE_DISTANCE_METRIC 1

#define DETAIL_LAYERS 3
#define DETAIL_SCALE 40.0
#define DETAIL_TEX_MAX_RANGE 10000.0
#define DETAIL_TEX_MIN_RANGE 1500.0
#define ENABLE_DETAIL_TEX 0

#define TEX_MIN_RANGE 2500.0
